###------------------------------------------------------------------------------------------###
###-------------------------------------Configuration-----------------------------------###
###------------------------------------------------------------------------------------------###
data_root: "results/assemblies" # data root of fastq.gz files
threads: 8
mask_label:
  label: "HSat2"
