# workflows/rules/plot.smk
import os, re, csv, glob, subprocess
from pathlib import Path
from snakemake.shell import shell
from importlib.resources import files as _pkg_files
from snakemake.io import glob_wildcards

try:
    _PKG_TOOLS = Path(_pkg_files("vallescope.resources").joinpath("tools")).resolve()
except Exception:
    _PKG_TOOLS = Path(__file__).resolve().parents[2] / "tools"
_REPO_TOOLS = Path.cwd() / "workflows" / "tools"

def _tool(name: str) -> str:
    for base in (_PKG_TOOLS, _REPO_TOOLS):
        cand = base / name
        if cand.exists():
            return str(cand)
    return str(_PKG_TOOLS / name)

DATA_ROOT   = config["data_root"]
THREADS     = int(config.get("threads", 8))
ALPHA_TARGET = int(config.get("alpha_target", 1))
GAP_BETA     = int(config.get("gap_beta", 20))

PROJECT_ROOT    = os.path.join(DATA_ROOT, "..")
RESULT_ROOT     = os.path.join(PROJECT_ROOT, "data")
ANCHOR_ROOT     = os.path.join(PROJECT_ROOT, "anchor")
PLOT_ROOT       = os.path.join(PROJECT_ROOT, "plot")

SAMPLES, BASES = glob_wildcards(f"{RESULT_ROOT}" + "/{sample}/censat/{base}.censat.bed")
PAIRS = list(zip(SAMPLES, BASES))

K_MER        = 15
MIN_JACCARD  = 0.6
MIN_SAMPLES  = 3
MAX_MED_RES  = 20000
MIN_UKF_OPT  = ""
MIN_MAPP_OPT = ""

PLOT_DPI     = 300
PLOT_W       = 10
PLOT_H       = 6

def afilfa_path(s, b):
    return os.path.join(ANCHOR_ROOT, s, b, "anchor_scoring", f"{b}.filtered.anchors.fa")

def afiltsv_path(s, b):
    return os.path.join(ANCHOR_ROOT, s, b, "anchor_scoring", f"{b}.filtered.anchors.tsv")

def afilbed_path(s, b):
    return os.path.join(ANCHOR_ROOT, s, b, "anchor_scoring", f"{b}.filtered.anchors.bed")

def gapbed_path(s, b):
    return os.path.join(ANCHOR_ROOT, s, b, "anchor_scoring", f"{b}.gap.anchors.bed")

def all_beds(wildcards=None):
    return sorted({afilbed_path(s, b) for s, b in PAIRS})

def all_fastas(wildcards=None):
    return sorted({afilfa_path(s, b) for s, b in PAIRS})

def all_tsvs(wildcards=None):
    return sorted({afiltsv_path(s, b) for s, b in PAIRS})

def all_bases(wildcards=None):
    return sorted({b for _, b in PAIRS})

def all_gapbeds(wildcards=None):
    return sorted({gapbed_path(s, b) for s, b in PAIRS})

def multitsv_path():
    return os.path.join(PLOT_ROOT, "vs.bundles.tsv")

def corpng_path():
    return os.path.join(PLOT_ROOT, "vs.bundles.png")

def paf_path():
    return os.path.join(PLOT_ROOT, "output.paf")

def syri_ready_paf_path():
    return os.path.join(PLOT_ROOT, "output.syri_ready.paf")

MTSV_TARGETS      = [multitsv_path()]
PAC_TARGETS       = [corpng_path()]
PAF_TARGETS       = [paf_path()]
SYRI_PAF_TARGETS  = [syri_ready_paf_path()]

# Source files generated by upstream anchoring steps.
# Keep len100 here if the upstream scripts still generate len100-named files.
def ancplot_path(s, b):
    return os.path.join(
        ANCHOR_ROOT,
        s,
        b,
        "anchoring_data",
        "anchors",
        f"{b}.masked.len100.region.png",
    )

def bigwig_path(s, b):
    return os.path.join(
        ANCHOR_ROOT,
        s,
        b,
        "anchoring_data",
        "anchors",
        f"{b}.masked.len100_smooth.bw",
    )

def masked_path(s, b):
    return os.path.join(RESULT_ROOT, s, "masked", f"{b}.masked.fasta")

def all_masked_fastas(wildcards=None):
    return sorted({masked_path(s, b) for s, b in PAIRS})

PNG_SRC = [ancplot_path(s, b) for s, b in PAIRS]
BW_SRC  = [bigwig_path(s, b)  for s, b in PAIRS]
BED_SRC = [afilbed_path(s, b) for s, b in PAIRS]

def at_root(p):
    return os.path.join(PROJECT_ROOT, os.path.basename(p))

def at_root_freq_name(p):
    """
    Copy visualization files to results/ root with user-facing freq names.

    Example:
      sample.masked.len100.region.png -> sample.masked.freq.region.png
      sample.masked.len100_smooth.bw  -> sample.masked.freq_smooth.bw

    The upstream files can still keep their original len100 names.
    """
    name = os.path.basename(p)
    name = name.replace(".masked.len100.region.png", ".masked.freq.region.png")
    name = name.replace(".masked.len100_smooth.bw", ".masked.freq_smooth.bw")
    return os.path.join(PROJECT_ROOT, name)

PNG_DST = [at_root_freq_name(p) for p in PNG_SRC]
BW_DST  = [at_root_freq_name(p) for p in BW_SRC]
BED_DST = [at_root(p) for p in BED_SRC]

def _tool_path(name: str) -> Path:
    return Path(_tool(name)).resolve()

def corpng_dst_path():
    return os.path.join(PROJECT_ROOT, os.path.basename(corpng_path()))

def paf_dst_path():
    return os.path.join(PROJECT_ROOT, os.path.basename(paf_path()))

def syri_ready_paf_dst_path():
    return os.path.join(PROJECT_ROOT, os.path.basename(syri_ready_paf_path()))

rule all:
    input:
        PAC_TARGETS,
        corpng_dst_path(),
        PNG_DST,
        BW_DST,
        BED_DST,
        paf_out = paf_dst_path(),
        syri_paf_out = syri_ready_paf_dst_path(),
        paf_ok = ".stages/export_paf.ok"

rule stage_multi_ok:
    input:
        MTSV_TARGETS
    output:
        ".stages/multi.ok"
    shell:
        r"""
        mkdir -p .stages
        touch {output}
        """

rule stage_corr_ok:
    input:
        PAC_TARGETS
    output:
        ".stages/corr.ok"
    shell:
        r"""
        mkdir -p .stages
        touch {output}
        """

rule stage_paf_ok:
    input:
        PAF_TARGETS
    output:
        ".stages/paf.ok"
    shell:
        r"""
        mkdir -p .stages
        touch {output}
        """

rule stage_syri_paf_ok:
    input:
        SYRI_PAF_TARGETS
    output:
        ".stages/syri_paf.ok"
    shell:
        r"""
        mkdir -p .stages
        touch {output}
        """

rule families_one:
    input:
        beds   = all_beds,
        fastas = all_fastas,
    output:
        tsv = multitsv_path(),
        png = corpng_path()
    params:
        script       = _tool("score_filter_anchors_multi.py"),
        outdir       = f"{PLOT_ROOT}",
        outpref      = f"{PLOT_ROOT}/vs",
        beds_csv     = lambda w, input: ",".join(input.beds),
        fastas_csv   = lambda w, input: ",".join(input.fastas),
        alpha_target = ALPHA_TARGET,
        gap_beta     = GAP_BETA,
    threads:
        THREADS
    shell:
        r"""
        echo "{params.outdir}"
        set -euo pipefail
        mkdir -p "{params.outdir}"
        python "{params.script}" \
            --beds "{params.beds_csv}" \
            --fastas "{params.fastas_csv}" \
            --out-prefix "{params.outpref}" \
            --alpha-target {params.alpha_target} \
            --gap-beta {params.gap_beta}
        """

rule make_paf:
    input:
        barrier = ".stages/corr.ok",
        tsv     = multitsv_path(),
        fastas  = all_masked_fastas,
    output:
        paf = paf_path(),
    params:
        script = _tool("vallescope_bundles_to_cigar_paf.py"),
    threads:
        THREADS
    run:
        fas = list(input.fastas)
        if len(fas) != 2:
            raise ValueError(f"make_paf expects exactly 2 FASTA files, got {len(fas)}: {fas}")

        shell(r"""
            set -euo pipefail
            python "{params.script}" \
                --bundles-tsv "{input.tsv}" \
                --ref-fa "{fas[0]}" \
                --qry-fa "{fas[1]}" \
                --out-paf "{output.paf}" \
                --threads {threads} \
                --minimap2-preset asm5 \
                --flank 0 \
                --max-bundle-bp 100000000
        """)

rule patch_paf_for_syri:
    input:
        barrier = ".stages/paf.ok",
        paf     = paf_path(),
        fastas  = all_masked_fastas,
    output:
        paf = syri_ready_paf_path(),
    params:
        script = _tool("paf_gap_patch_unialigner_to_syri_paf.py"),
        unialigner_bin = str(
            (
                _tool_path("paf_gap_patch_unialigner_to_syri_paf.py").parent
                / "unialigner"
                / "tandem_aligner"
                / "build"
                / "bin"
                / "tandem_aligner"
            ).resolve()
        ),
        flank = 10000,
        max_gapfill = 70000,
        keep_overlap = 200,
        bridge_tol = 500,
        min_split_flank = 500,
    threads:
        THREADS
    run:
        fas = list(input.fastas)
        if len(fas) != 2:
            raise ValueError(f"patch_paf_for_syri expects exactly 2 FASTA files, got {len(fas)}: {fas}")

        unialigner_cmd = (
            f'tmpdir="${{OUT}}.dir"; rm -rf "$tmpdir"; mkdir -p "$tmpdir"; '
            f'"{params.unialigner_bin}" --first "{{REF}}" --second "{{QRY}}" -o "$tmpdir" '
            f'>/dev/null 2>&1 && cp "$tmpdir/cigar.txt" "{{OUT}}"'
        )

        shell(r"""
            set -euo pipefail
            python3 "{params.script}" \
                --in-paf "{input.paf}" \
                --ref-fa "{fas[0]}" \
                --qry-fa "{fas[1]}" \
                --out-paf "{output.paf}" \
                --flank {params.flank} \
                --max-gapfill {params.max_gapfill} \
                --keep-overlap {params.keep_overlap} \
                --bridge-tol {params.bridge_tol} \
                --unialigner-cmd '{unialigner_cmd}' \
                --keep-failed \
                --split-on-pure-insertion \
                --min-split-flank {params.min_split_flank}
        """)

rule export_copy_files:
    input:
        bundle_png = corpng_path(),
        pngs = PNG_SRC,
        bws  = BW_SRC,
        beds = BED_SRC
    output:
        bundle_png_out = corpng_dst_path(),
        pngs_out = PNG_DST,
        bws_out  = BW_DST,
        beds_out = BED_DST
    params:
        outdir = PROJECT_ROOT
    run:
        shell(r"""
            set -euo pipefail
            mkdir -p "{params.outdir}"
            cp -a "{input.bundle_png}" "{output.bundle_png_out}"
        """)

        for src, dst in zip(list(input.pngs), list(output.pngs_out)):
            shell(r"""
                set -euo pipefail
                cp -a "{src}" "{dst}"
            """)

        for src, dst in zip(list(input.bws), list(output.bws_out)):
            shell(r"""
                set -euo pipefail
                cp -a "{src}" "{dst}"
            """)

        for src, dst in zip(list(input.beds), list(output.beds_out)):
            shell(r"""
                set -euo pipefail
                cp -a "{src}" "{dst}"
            """)

rule export_pafs:
    input:
        barrier = ".stages/syri_paf.ok",
        paf = paf_path(),
        syri_paf = syri_ready_paf_path()
    output:
        paf_out = paf_dst_path(),
        syri_paf_out = syri_ready_paf_dst_path(),
        ok = ".stages/export_paf.ok"
    params:
        outdir = PROJECT_ROOT
    shell:
        r"""
        set -euo pipefail
        mkdir -p "{params.outdir}"
        cp -a "{input.paf}" "{output.paf_out}"
        cp -a "{input.syri_paf}" "{output.syri_paf_out}"
        touch {output.ok}
        """
